-- RV Manager Enterprise 4.2
-- Archivio simulazioni busta paga.

create table if not exists public.payroll_simulations (
    id bigint generated by default as identity primary key,
    job_title text not null,
    ccnl text not null,
    sector text,
    level text not null,
    monthly_hours numeric(10,2) not null default 0,
    gross_monthly numeric(12,2) not null default 0,
    net_monthly numeric(12,2) not null default 0,
    company_cost_monthly numeric(12,2) not null default 0,
    parameters jsonb not null default '{}'::jsonb,
    result jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.payroll_simulations enable row level security;
revoke all on public.payroll_simulations from anon, authenticated;

create index if not exists payroll_simulations_created_at_idx
    on public.payroll_simulations (created_at desc);
