-- RV Manager Enterprise 2.0: registro eventi aziendali

create table if not exists audit_events (
    id bigint generated by default as identity primary key,
    event_type text not null,
    title text not null,
    severity text not null default 'info'
        check (severity in ('info', 'warning', 'critical', 'success')),
    employee_id bigint references employees(id) on delete set null,
    actor_user_id uuid,
    entity_type text,
    entity_id text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_audit_events_created
on audit_events(created_at desc);

create index if not exists idx_audit_events_employee
on audit_events(employee_id, created_at desc);

alter table audit_events enable row level security;
