-- RV Manager Enterprise 4.1
-- Centro backup manuale e automatico.

create table if not exists public.backup_registry (
    id bigint generated by default as identity primary key,
    backup_type text not null check (backup_type in ('manuale', 'automatico')),
    file_name text not null,
    storage_path text not null,
    size_bytes bigint not null default 0,
    checksum_sha256 text not null,
    status text not null default 'completato',
    error_message text,
    created_at timestamptz not null default now()
);

create table if not exists public.backup_settings (
    id integer primary key default 1 check (id = 1),
    enabled boolean not null default false,
    frequency text not null default 'giornaliero'
        check (frequency in ('giornaliero', 'settimanale', 'mensile')),
    run_hour integer not null default 2 check (run_hour between 0 and 23),
    retention_count integer not null default 30
        check (retention_count between 3 and 365),
    last_run_at timestamptz,
    next_run_at timestamptz,
    updated_at timestamptz not null default now()
);

insert into public.backup_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.backup_registry enable row level security;
alter table public.backup_settings enable row level security;

-- Le operazioni sono riservate al service role usato dal backend.
revoke all on public.backup_registry from anon, authenticated;
revoke all on public.backup_settings from anon, authenticated;

insert into storage.buckets (id, name, public)
values ('system-backups', 'system-backups', false)
on conflict (id) do update set public = false;
